/**
 * Self-host the interface typeface.
 *
 * Fetches the Google Fonts stylesheet for IBM Plex Sans, keeps only the `latin`
 * and `latin-ext` subsets, downloads those woff2 files into public/fonts, and
 * writes a local @font-face stylesheet.
 *
 * Why self-hosted rather than a hosted stylesheet link: the application has to
 * work offline, behind a captive network, and embedded in another site, and a
 * third-party font request is an availability dependency the application should
 * not have. It also removes a render-blocking cross-origin round trip.
 *
 * Run with: node scripts/fetch-fonts.mjs
 * The output is committed, so this only needs re-running when the face changes.
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'public', 'fonts');
const CSS_OUT = join(ROOT, 'src', 'fonts.css');

/* 400 for body copy, 500 for control labels, 600 for headings and figures.
   450 is dropped: the difference from 400 is invisible at 12px and it costs a
   subset download for nothing. */
const WEIGHTS = [400, 500, 600];
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const FAMILY = 'IBM Plex Sans';
const SPEC = `${FAMILY.replace(/ /g, '+')}:wght@${WEIGHTS.join(';')}`;

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const url = `https://fonts.googleapis.com/css2?family=${SPEC}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`font stylesheet request failed: ${res.status}`);
  const css = await res.text();

  /* The stylesheet is a sequence of `/* subset *\/` comments each followed by one
     @font-face block. Split on the comments so the subset name is known. */
  const blocks = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let m;
  while ((m = re.exec(css))) blocks.push({ subset: m[1], face: m[2] });
  if (!blocks.length) throw new Error('no @font-face blocks found in the font stylesheet');

  const out = [];
  let downloaded = 0;

  for (const { subset, face } of blocks) {
    if (!KEEP_SUBSETS.has(subset)) continue;
    const weight = /font-weight:\s*(\d+)/.exec(face)?.[1];
    if (!weight || !WEIGHTS.includes(Number(weight))) continue;

    const src = /src:\s*url\(([^)]+)\)/.exec(face)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(face)?.[1];
    if (!src) continue;

    const file = `plex-sans-${weight}-${subset}.woff2`;
    const bin = await fetch(src, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`font file download failed: ${src}`);
    const bytes = Buffer.from(await bin.arrayBuffer());
    writeFileSync(join(OUT_DIR, file), bytes);
    downloaded++;
    out.push({ file, weight, range, bytes: bytes.length, subset });
  }

  if (!out.length) throw new Error('no latin subsets matched; check the weights and family name');

  /* Local stylesheet. Only the weights and subsets actually downloaded are
     declared, so the browser never requests a file that does not exist. */
  const face = out
    .map(
      (f) => `@font-face {
  font-family: '${FAMILY}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
${f.range ? `  unicode-range: ${f.range};` : ''}
}`,
    )
    .join('\n\n');

  const header = `/*
 * Self-hosted interface typeface.
 *
 * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand. Re-run that script
 * to change the face or the weights.
 *
 * ${FAMILY} is used for the interface text: a technical grotesque with a large
 * x-height that stays legible at the 12px base size this application runs at,
 * which matters because the panels are dense and mostly small type. The
 * monospace face is a system stack, because the numerals that need tabular
 * alignment are in tables and code identifiers rather than in prose.
 */

${face}
`;
  writeFileSync(CSS_OUT, header, 'utf8');

  const total = out.reduce((a, f) => a + f.bytes, 0);
  console.log(
    `wrote ${downloaded} font files (${(total / 1024).toFixed(0)} KB) and src/fonts.css\n` +
      out.map((f) => `  ${f.file} ${(f.bytes / 1024).toFixed(0)} KB`).join('\n'),
  );
}

if (!existsSync(join(ROOT, 'package.json'))) {
  throw new Error('run this from the repository root');
}
await main();